server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver:${DB_URI://localhost};databaseName=fgc_im_test;encrypt=true;trustServerCertificate=true
    username: ${SQLUSER:sa}
    password: ${SQLPASS:fL200110$}
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      platform: mssql

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  token:
    key: j3H5Ld5nMmGWyULy2xwp7gfSH++NgKXsJMq20vpfd+8=t
    expiration: 60
